[package]
name = "wasm_demo"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

web-sys = { version = "0.3.2", features = ["Window", "Document", "Node", "HtmlElement", "Element"] }

[dependencies]
wasm-bindgen = "0.2"

[dependencies.web-sys]
version = "0.3"
features = []
